"""second migration

Revision ID: deee2568bfd3
Revises: 822b4aee4eba
Create Date: 2025-10-25 23:17:30.649855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deee2568bfd3'
down_revision: Union[str, Sequence[str], None] = '822b4aee4eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column('number_of_servings', sa.Integer(), nullable=False))
    op.add_column('foods', sa.Column('last_eaten_at', sa.Date(), nullable=False))
    op.add_column('foods', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'updated_at')
    op.drop_column('foods', 'last_eaten_at')
    op.drop_column('foods', 'number_of_servings')
    # ### end Alembic commands ###
